---
title: "Summary of income analysis"
output: 
  html_notebook:
    code_folding: hide
    number_sections: no
    toc: yes
    toc_depth: 1
    css: "scr/styles.css"
    
---

From previous work done comparing SHS and HBAI data, we expect the average total income to be matching fairly well, even if the individual income components might not match well enough for detailed analysis due to the different remits of the two surveys and resulting methods. Here, we look at how the individual income components differ between the surveys and how that might affect different groups of the population differently.

We compared SHS 2018 income data (the new, broader definition) with HBAI 2018/19 income data. For the HBAI data, we used net income without the top-income adjustment. Except for this, the income definition we used is the same as that used for official household income and poverty statistics. This definition includes some components that are not available in the SHS, such as child income, and deductions (council tax, pension contributions, maintenance and child support payments, parental contributions to students living away from home, and student loan repayments). Of the deductions, council tax is the only information (indirectly) available in the SHS, and we deducted it from SHS household income (but not water and sewerage charges). We calculated council tax using the council tax bands and imputing single-person discounts. Where the concil tax band was missing (most of Shetland in the 2018 dataset), we assigned council tax band B, the most common band. 

We also looked at administrative data on benefits to quantify the amount of benefit underreporting in the SHS (and the HBAI).

Note that all income discussed here is net income after benefits and tax, and not taking housing costs into account (= before housing cost).

For the analysis, 95% confidence intervals (C.I.) of the median were calculated using a bootstrapping method. For the HBAI, the boostrapped C.I.s do not account for the complex survey design. They are therefore only illustrative and may be wider. The C.I.s calculated for the SHS take into account the survey design (stratification by council areas).

In order to make good comparisons across surveys, we recoded some common variables. For example, the definition of a child in the SHS was recoded to match that of the HBAI (i.e. includes 17-19 year-olds living at home, not married, and in full-time non-advanced education). Also, households in the SHS where the highest income householder (which is by definition the household head) is a student, but has earnings income and working hours, were recoded to full- or part-time employee households. This is because of differences in the definition of economic status between the two surveys. In the FRS ILO definition used here, students with jobs would be considered in work, whereas in SHS they would be considered students.

The sections mentioned below refer to the accompanying document with charts and tables.

# Earnings higher 

Median and mean earnings are higher in the SHS compared to the HBAI, driven by both, slightly higher average employed earnings, and much higher average self-employed earnings. However, _aggregated_ total earnings are lower because fewer households in the SHS than in the HBAI report that they have any earnings (section 1.3). 

Median earnings of households where the head is employed (both, full- or part-time) match fairly well between surveys, but those where the head is self-employed have much higher earnings in the SHS. Checking with the (yet unpublished SHS 2019) dataset shows that this high level of self-employed earnings is consistent across years. This level may be much higher than in the HBAI because the SHS doesn't deduct allow negative earnings. However, even when negative earnings in the HBAI were set to 0, the large difference in self-employed earnings persisted. It is possible that it is caused by questionnaire wording and survey time spent on this area (section 1.3).

Across income deciles, median earnings match fairly well. There is more earnings variation in the top decile and the lowest two deciles, and less in the 3rd to 9th decile. However, the 3rd income decile is the only one where median earnings in the SHS are markedly lower than in the HBAI. Note that this is the income decile where the poverty threshold is typically located, and small differences in the income distribution here can have a big effect on poverty numbers (section 1.2).

Looking at council areas, note that HBAI data cannot be meaningfully analysed at a sub-Scotland level, as the weighting regime for the survey doesn’t account for geography within Scotland. There are therefore large discrepancies for council areas across surveys. Having said that, if we do compare those (ten) council areas where household numbers are similar between SHS and HBAI (difference < 50%), median earnings match fairly well (section 1.5).

# Benefits lower 

```{r bendiff, echo=FALSE}

bendiff <- tidydata %>%
  group_by(survey, type) %>%
  summarise(amount = sum(amount*hhwgt*equ)) %>%
  spread(survey, amount) %>%
  mutate(totdiff = HBAI[1] - SHS[1],
         diff = HBAI - SHS,
         diffcontr = diff/totdiff) %>%
  filter(type == "ben") %>%
  select(diffcontr) %>%
  mutate(diffcontr = percent(diffcontr, 1)) %>% pull()

```

Generally, benefit income is lower in the SHS than in the HBAI. The lower benefit income in the SHS explains `r bendiff` of the total income difference between these two surveys. (Note that when comparing benefit incomes, one should keep in mind that benefits in the HBAI are already underreported (to varying degrees)). The lower benefit income in the SHS is caused by: fewer households reporting they receive a benefit or households not reporting all the benefits they receive, and households reporting (on average) smaller benefit payments (section 2.1).

**Working-age households** (defined here as households with no adults above state pension age) receive on average much lower benefits compared to pensioner households (section 2.1). Benefit income of working-age households in the top five income deciles is mainly made up of disability benefits, followed by Child Benefit. In the lower income deciles, average benefit income increases, and is made up of disability benefits and Child Benefit, and increasingly (with lower incomes) also with Tax Credits, Housing Benefit and Universal Credit. Benefit income of the bottom income decile is quite low (lower than in deciles 2-4), a common feature of survey-based income data, and probably due to various reporting errors. When comparing benefit income for working-age households _across the two surveys_, it appears that disability benefits, Tax Credits, Child Benefit and Universal Credit are lower in the SHS  (section 2.2). We will see later that these are underreported in the SHS compared to the HBAI, as are almost all benefits (section 3). The lower income deciles also show large data variability with large uncertainty for both surveys (section 2.2).

**Pensioner households** have on average a much higher benefit income due to the State Pension, which is the main benefit income source. This is followed by disability benefits, Housing Benefit and Pension Credit. Average benefit incomes for pensioner households are quite variable across all income deciles and in both surveys, with SHS central estimates consistently below the HBAI estimates. Median benefit income C.I.s don't overlap in the bottom and the 7th income decile, with the SHS estimates far below the HBAI ones. The lower benefit income in the SHS is due to underreporting of State Pension and other benefits (section 2.2).

Median benefit income across the two surveys matches better for some **household types** than for others. For example, median benefit income of households with two adults with children, or households with one adult and one pensioner match well. On the other hand, median benefit incomes for single adult households and households with two pensioners differ considerably, and C.I.s don't overlap at all (section 2.3). 

For **single adult households**, this is caused by people underreporting disability benefits in the SHS, see [Single adults' benefit incomes][Single adults' benefit incomes]. 

For **pensioner couple households**, the difference in median benefit income between the two surveys is largely due to underreporting of the amount of state pension received. This affects households with two pensioners most. In addition, many pensioners, in particular those who are single, do not report receiving any state pension at all (although these are only included in these summary statistics if they report some other benefit income) (section 6).

Looking at household **economic status**, median benefit incomes for households where the highest income householder is a full-time employee match well between surveys and show a small benefit amount and little variability. There is more variability and discrepancy in median benefit incomes for the Other Inactive group. All other groups show considerable differences in median benefit incomes, with the SHS amount consistently lower. Median benefit income C.I.s from SHS and HBAI do not overlap at all for retired and disabled households. Reasons for this are largely non-reporting of state pension, and under- and non-reporting of disability benefits (section 2.4).

Looking across **council areas**, we need to remind ourselves that the HBAI is not designed for sub-Scotland level analysis, and household numbers in each council area are not designed to be accurate. However, removing those council areas with very large (>50%) discrepancies in number of households, and also excluding council areas with too small sample sizes, we're left with 13 council areas for comparison across surveys. In these, benefit incomes match reasonably well with SHS benefit income consistently slightly below HBAI benefit income, but with C.I.s that overlap, except for Fife (section 2.5). We don't know what the issue is in Fife, as it has an average number of pensioners and is also not one of the council areas that heavily depend on benefits (section 8). Maybe this discrepancy just reflects that the HBAI isn't designed for sub-Scotland analysis.

## Benefit types

The largest benefit by far is the State Pension, which makes up almost half of all benefit income. This is followed by the combined disability and carers' benefits, followed by Tax Credits, Housing Benefit, Child Benefit, Universal Credit, Pension Credit, and many smaller benefits (section 3).

All of the big benefits except for Housing Benefit are underreported in the SHS compared to the HBAI. (Note that the HBAI underreports all benefits compared to administrative data.) This could be due to underreporting of the amount received, not reporting a benefit, or a combination of both. Underreporting of State Pension and disability benefits explains most of the benefit income differences between the two surveys (section 3).

The underreporting of all but one benefits means that those household types with a large share of their income coming from benefits will show a lower income in the SHS compared to the HBAI. This affects households with low or no earnings: pensioners, who receive a large part of their income through the state pension (and other, smaller benefits such as disability and carers' benefits, Pension Credit and Winter Fuel Payment), and households with disabled household members who receive disability and carers' benefits. I expect it also affects other low-earnings households through Tax Credits and Universal Credit. These households will show too low an income in the SHS.

To add more detail, **State Pension** is fairly well covered in the HBAI (93%), but less so in the SHS (78%). This discrepancy explains 48% of the total benefit income difference between HBAI and SHS. It originates in a smaller number of individuals in the SHS reporting that they receive State Pension, even though the average payments are comparable between surveys (section 6).

Combined **disability and carers' benefits** are covered to 73% in the HBAI, and only to 56% in the SHS. These include Disability Living Allowance, Personal Independence Payment, Attendance Allowance, Employment Support Allowance, Carers' Allowance, Severe Disablement Allowance, and Industrial Injuries Disablement Benefit. I included Carers' Allowance in this list as I expect most carers to live in the same household as the person they care for. The discrepancy between HBAI and SHS disability benefit incomes explains a further 30% of the total benefit income difference between HBAI and SHS. Disability benefits in the SHS are subject to both, underreporting of the amount, and non-reporting of receipt (sections 3 and 3.2).

**Tax credits** are also underreported in the SHS compared to the HBAI, explaining a further 9% of the benefit income difference between the surveys. A large part of this is part-time employee households underrerporting the amount of Tax Credit they get. Both surveys vastly underreport Tax Credit compared to admin data (sections 3 and 3.3). 

**Housing Benefit** is underreported to a similar degree in both surveys (section 3.4).

**Child Benefit** income in the SHS is only slightly lower than in the HBAI, due to some households with two adults and children not reporting receipt of this benefit (section 3.5).

**Universal Credit** and **Pension Credit** are both vastly underreported in the SHS, explaining another 8% each of the total benefit income difference between HBAI and SHS. For both benefits, the received amounts are underreported. In addition, there is allso a lot of non-reporting of Pension Credit receipt (sections 3.6 and 3.7).

## Single adults' benefit incomes lower

Many more single adult households in the SHS than the HBAI report (any) benefit income, and therefore _aggregated_ benefit income for single adult households is higher in the SHS compared to the HBAI. However, we have seen that for this household type, _average_ benefit income is much lower in the SHS. This is mainly driven by underreporting of disability benefits in the SHS, which, combined, are the most valuable benefits for this group (section 4).

# Investment income much lower

Investment income is hugely underreported in the SHS compared to the HBAI, even though we are using the HBAI data before top-income adjustments (which would correct top incomes upwards). The massively lower investment income in the SHS is largely due to non-reporting of any investment income. Most of investment income is held by retired households, and by working-age two adult households; these are therefore the groups whose income is affected more. Similarly, most of investment income is held by the richest households (section 5).

# Pensioners' incomes too low

**Single pensioner** and **pensioner couple** households get the major part of their income from benefits, which is mainly the State Pension. As the State Pension is underreported, household income is underrerported for these household types. The underreporting of State Pension is due to both, underreporting of the amount, and non-reporting of receiving the benefit. Many single pensioners in particular did not report that they received any State Pension at all (section 6). 

In addition to differences in benefit income (which is mainly the state pension), there are also differences in occupational pensions and investment income. The difference in investment income is mostly due to non-reporting of investment income in the SHS compared to the HBAI. It should be noted that most of investment income in Scotland goes to retired households. Similarly, fewer people in the SHS report any occupational pension income, although in the aggregate, the SHS occupational pensions income is only slightly below that in the HBAI (sections 5 and 6).

Households with **one working-age adult and one pensioner** get large parts of their income through earnings, followed by occupational pensions and benefits (section 6). This means that this group is less affected by underreported benefit income, and we will see that the median total income of this group matches better across surveys compared to single pensioner or pensioner couple households (section 9.6).

And as mentioned before, **Pension Credit**, an income-related benefit for pensioners is subject to both, considerable underreporting of the amount, and non-reporting of receipt for SHS, compared to HBAI. This also contributes to the benefit income underreporting for pensioners.

# Self-employed incomes higher

Households where the head is self-employed had higher incomes in the SHS, driven by much higher earnings. This is consistent with the (yet unpublished) SHS 2019 data, so not an artefact. On the other hand, benefit income is lower, but has much less of an impact as it is on average much less important than earnings.

Reasons for the higher earnings of the self-employed in the SHS could include that the SHS my not fully account for self-employed losses, or not in the same way as the HBAI. For example, the SHS doesn't accept negative earnings responses. Also, the definitions of self-employment may differ between surveys.

Note that households where the head is self-employed make up only 7% of all households (according to SHS 2018), so maybe this issue isn't very important.

# Income components 

Total income aggregated to the whole of Scotland is largely made up of earnings, followed by benefits (which include the state pension) and occupational pensions (section 8).

Overall, SHS total income is `r incdiff` lower than HBAI total income. The differences come mainly from lower benefit and much lower investment income in the SHS, and then also from lower occupational pensions. Income from earnings is higher in the SHS. Other income components are relatively small and therefore contribute less to the overall differences in income (section 8).

We have seen that the lower benefit income mostly affects pensioners (through the state pension) and households with disabled household members (through disability benefits) (sections 2.3, 2.4, 4).

We have also seen that most of the investment income goes to the wealthiest households. This will affect the income distribution most at the top, and might therefore not matter as much when looking at low income households. However, a large part of investment income goes to retired households, so this could exacerbate the income underreporting of these households even more (sections 5 and 8).

For all **income quintiles**, the aggregated total income is higher in the HBAI compared to the SHS, with the largest differences at the top quintile. For the lowest income quintile, HBAI benefits are higher, but this is partially compensated for by lower HBAI earnings. In the second income quintile (this is where the poverty threshold sits), the difference is mainly driven by higher earnings in the HBAI, even though HBAI benefits here are lower. In the third and fourth income quintiles, HBAI earnings are again lower than SHS earnings. However, higher HBAI benefit income, occupational pensions and investment incomes lead to a higher total income in the HBAI in these quintiles. In the top quintile, total income differences are due to higher HBAI incomes from all major sources, including earnings, but in particular investment income and occupational pensions (section 8).

The lower the total income is, the less important earnings and the more important benefits become.

As for **regional underreporting**, this is difficult to ascertain from comparison with HBAI data, because the HBAI's weighting regime doesn't allow sub-Scotland analysis. However, we would expect underreported incomes in those local areas that have a high share of their income coming from benefits, and also in local areas with many pensioners (whose main income source is the State Pension, a benefit).

The six council areas with the highest benefit shares are, according to SHS data, Dumfries & Galloway, Inverclyde, North Ayrshire, East Ayrshire, West Dunbartonshire, and Dundee City. The eight council areas with the largest proportion of pensioners are Na h-Eileanan Siar, Argyll & Bute, Dumfries & Galloway, South Ayrshire, Scottish Borders, Orkney Islands, Angus, and Perth & Kinross (section 8).

Breaking the country down to urban and rural areas, small towns and other (not large) urban areas have the highest shares of benefit income. Remote small towns and remote rural areas on the other hand have the largest proportions of pensioners (section 8).

# Total income overall

Having identified some issues in the measurement of the various _income components_, we will now see how these affect total income.

The income **distributions** in the SHS and the HBAI look largely similar, with the SHS income distribution being slightly wider, and the SHS **median** slightly lower (`r comma(SHSmedian, prefix = "£")` versus `r comma(HBAImedian, prefix = "£")`). Near the relative poverty threshold, the SHS cumulative income curve is higher, meaning more households sit below that threshold in the SHS compared to the HBAI. This means that more people are considered to be in relative poverty when using the SHS dataset compared to the HBAI dataset (section 9.1).

The nine income decile points (the thresholds in each dataset that split the populations into ten equal-sized groups) are slightly higher for the SHS for high incomes, level at the sixth decile point, and diverge towards lower incomes, with SHS incomes being markedly lower. This shows that more households in the SHS have lower incomes compared to the HBAI, whereas the high income end of the distribution matches better between surveys. We have seen this is largely caused by benefit underreporting and higher earnings in the SHS (relative to the HBAI). The lower the income, the more important benefit income becomes, and the more affected total income is by benefit underreporting (section 9.2).

Median income C.I.s overlap to some degree for all 17 **council areas** where we compared surveys. We excluded those council areas where the HBAI household populations were too far off (> 50% compared to SHS household population). For some council areas, the overlaps are only marginal, such as East Dunbartonshire, Aberdeenshire, Stirling, and Moray, with Aberdeenshire having a  relatively large HBAI sample size. Note also, that none of these areas were noted earlier for particularly high proportions of pensioners or benefit income shares. However, C.I.s for all council areas and for both surveys are fairly wide, showing much income variation within each council area (section 9.3).

Median incomes match fairly well for **urban** and accessible rural areas. Median incomes in remote areas match slightly less well, but also have fairly wide C.I.s (section 9.4).

Median incomes of **working-age adults** and **children** match well, but **pensioners**' incomes are much lower in the SHS, and C.I.s do not overlap. We saw that this is largely due to underreporting of the State Pension, as well as occupational pensions and investment income (sections 9.5 and 6).

Incomes for most **household types** match well, except, again, for pensioners, whose income is much lower in the SHS. Incomes of households with 3 or more adults (and no children) have very wide C.I.s, indicating large variation of incomes in this group. Single adult incomes match surprisingly well, seeing how much benefit income is underreported for this group. However, earnings in this group are higher in the SHS than the HBAI and appear to balance out the benefit underreporting (section 9.6).

Incomes of households where the household head (the highest income householder) is a **full- or part-time employee** match fairly well, which is no surprise as income from employed earnings also matches fairly well. Income of **self-employed households** varies widely and C.I.s do not overlap between the two surveys. We have seen that this is largely due to the much higher self-employed earnings reported in the SHS, for which the lower benefit income does not compensate (section 1.3). As expected, incomes of the **retired** don't match well, similarly to pensioners' incomes in the age group and household type breakdowns. Incomes of the **disabled** also don't match too well, due to undereporting of disability benefits, which are the main income source of these households (section 9.7).


# Open questions

- How well do housing costs match? There are some inherent differences between surveys of what's included as a housing cost. In the HBAI, housing costs include rent, mortgage interest payment, water and sewerage charges, and (structural) home insurance. In the SHS, housing costs include rent and _all mortgage payments_.

- In the analysis here, we didn't use the usual HBAI BHC income variable, but income without top-income adjustments. The reason for this is that the top-income adjusted income figures are only available for gross income, but not net income. The effect on the median is small. The HBAI median without top-income adjustment is `r comma(HBAImedian, prefix = "£", accuracy = 1)`, whereas the top-income adjusted median is £517. We expect higher incomes to be affected more.

- Self-employed earnings are much higher in the SHS compared to the HBAI. Also, the SHS doesn't allow negative earnings responses. The difference in self-employed earnings between surveys is probably due to the questionnaire wording and interview time spent on getting this information.

- can we calculate better confidence intervals for the HBAI data using the resamples dataset that DWP provide?

- how important is children's income? SHS doesn't collect information on this. Ipsos Mori report showed it made up 1% of single parents' income

- SHS doesn't ask about children's benefits such as child DLA. However, benefit income by household type doesn't look particulalry bad for households with children. Might need to look into this further for any breakdowns of child poverty by disability.

- Many pensioners in the SHS do not report that they receive state pension. Is this due to the question wording? Maybe model state pension instead of imputing it?

- Should we include recommendations for SHS questionnaire or editing changes? I.e. imputing state pensions, wording change for disability benefits to harmonise with FRS, etc.
